### ISSUE TITLE
Openwebstart version 1.9.0

### ISSUE THREAD

**Issue by pmonckton** [fatihusta/OpenWebStartRPM#1]
Is it possible you could modify your code to incorporate the new Openwebstart version 1.9.0. Thanks

**Comment by fatihusta** [comment]
You can build 1.9.0 without code modification. Did you try?

```sh
export OWS_VERSION=1.9.0
```

```sh
docker run \
       --rm \
       --workdir /root/ows \
       --volume $(pwd):/root/ows \
       fedora:36 \
       /bin/sh /root/ows/build.sh $OWS_VERSION $RPM_RELEASE
```

**Comment by fatihusta** [comment]
Also I added pre builded rpms. You can find into release page. https://github.com/fatihusta/OpenWebStartRPM/releases
